spring.datasource.url=jdbc:postgresql://localhost:5433/suplementos_store
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.application.name=fitnesspersonal
